
export const TIPS = [
    { id: 1, text: "El color del vino tinto se aclara con la edad, pasando de púrpura a teja.", icon: "palette" },
    { id: 2, text: "Para oler mejor el vino, agita la copa suavemente para oxigenarlo.", icon: "air" },
    { id: 3, text: "El 'retrogusto' es el sabor que persiste en la boca después de tragar.", icon: "face" },
    { id: 4, text: "La temperatura ideal para un vino tinto joven es de 14-16°C.", icon: "thermostat" },
    { id: 5, text: "El lúpulo aporta el amargor y el aroma a la cerveza.", icon: "local_florist" },
    { id: 6, text: "Un whisky 'Single Malt' proviene de una sola destilería.", icon: "factory" },
    { id: 7, text: "Los taninos causan esa sensación de sequedad en las encías.", icon: "dry" },
    { id: 8, text: "El término 'Crianza' en vinos españoles implica al menos 24 meses de envejecimiento.", icon: "hourglass_top" },
    { id: 9, text: "El Tequila solo puede producirse en México, principalmente en Jalisco.", icon: "map" },
    { id: 10, text: "El café 'Arábica' es más ácido y aromático que el 'Robusta'.", icon: "coffee" },
    { id: 11, text: "Si un vino huele a corcho húmedo o cartón, podría estar 'picado' (TCA).", icon: "warning" },
    { id: 12, text: "Las 'piernas' o 'lágrimas' del vino indican alcohol o azúcar, no calidad.", icon: "water_drop" },
    { id: 13, text: "El Gin obtiene su sabor principal de las bayas de enebro.", icon: "forest" },
    { id: 14, text: "Decantar un vino viejo ayuda a separar los sedimentos.", icon: "filter_list" },
    { id: 15, text: "Las copas de boca estrecha concentran los aromas.", icon: "wine_bar" },
    { id: 16, text: "El maridaje por contraste busca sabores opuestos (ej: Queso azul y vino dulce).", icon: "contrast" },
    { id: 17, text: "El maridaje por afinidad busca sabores similares (ej: Carne y vino potente).", icon: "handshake" },
    { id: 18, text: "El Sake no es un destilado, es un fermentado de arroz.", icon: "rice_bowl" },
    { id: 19, text: "El 'Terroir' incluye suelo, clima y tradición humana.", icon: "landscape" },
    { id: 20, text: "La acidez hace que el vino se sienta fresco y te haga salivar.", icon: "water" },
    { id: 21, text: "Los vinos blancos jóvenes suelen tener reflejos verdosos.", icon: "visibility" },
    { id: 22, text: "Un vino 'con cuerpo' se siente denso en la boca, como leche entera vs agua.", icon: "fitness_center" },
    { id: 23, text: "El Bourbon debe hacerse con al menos 51% de maíz.", icon: "grass" },
    { id: 24, text: "El Ron oscuro suele envejecerse en barricas carbonizadas.", icon: "mode_night" },
    { id: 25, text: "La espuma de la cerveza protege el aroma y evita la oxidación.", icon: "cloud" },
    { id: 26, text: "El Mezcal tiene un sabor ahumado porque el agave se cuece bajo tierra.", icon: "local_fire_department" },
    { id: 27, text: "El Vermut es un vino aromatizado con hierbas y especias.", icon: "local_bar" },
    { id: 28, text: "La fase visual es la primera: inclina la copa sobre un fondo blanco.", icon: "looks" },
    { id: 29, text: "Identificar 3 aromas distintos es un buen comienzo para cualquier cata.", icon: "looks_3" },
    { id: 30, text: "¡El mejor vino es el que a ti te gusta!", icon: "thumb_up" },
    { id: 31, text: "Decantar airea el vino; oxigenar ayuda a abrir aromas cerrados.", icon: "air" },
    { id: 32, text: "El defecto 'TCA' huele a perro mojado o periódico viejo.", icon: "pets" },
    { id: 33, text: "La tapa de rosca no significa mala calidad; preserva la frescura.", icon: "check_circle" },
    { id: 34, text: "Al abrir Champagne, gira la botella, no el corcho, para mayor seguridad.", icon: "celebration" },
    { id: 35, text: "El Oporto Ruby es joven y frutal; el Tawny es añejo y oxidativo.", icon: "invert_colors" },
    { id: 36, text: "El Jerez Fino se cría bajo velo de flor; el Oloroso es oxidativo.", icon: "local_florist" },
    { id: 37, text: "El Vermut abierto siempre debe guardarse en la nevera.", icon: "kitchen" },
    { id: 38, text: "La Absenta tradicional se sirve con agua helada y un terrón de azúcar.", icon: "water_drop" },
    { id: 39, text: "Tequila Blanco no tiene crianza; Reposado (2m-1a); Añejo (>1a).", icon: "schedule" },
    { id: 40, text: "El ahumado del Mezcal viene de cocer las piñas con leña.", icon: "fireplace" },
    { id: 41, text: "Además de enebro, el Gin suele llevar cilantro, angélica y cítricos.", icon: "eco" },
    { id: 42, text: "El Vodka busca ser neutro, pero la materia prima (trigo, papa) influye.", icon: "grain" },
    { id: 43, text: "El Ron Agrícola se hace de jugo de caña; el Industrial, de melaza.", icon: "agriculture" },
    { id: 44, text: "El Whisky de Islay (Escocia) es famoso por su intenso sabor a turba.", icon: "terrain" },
    { id: 45, text: "El Bourbon siempre debe envejecerse en barricas de roble nuevo.", icon: "inventory_2" },
    { id: 46, text: "El Whisky de Centeno (Rye) es más picante y seco que el Bourbon.", icon: "whatshot" },
    { id: 47, text: "El Whisky japonés busca el equilibrio y la precisión técnica.", icon: "balance" },
    { id: 48, text: "El Whiskey irlandés suele destilarse tres veces para mayor suavidad.", icon: "filter_3" },
    { id: 49, text: "Todo Cognac es Brandy, pero no todo Brandy es Cognac (región).", icon: "map" },
    { id: 50, text: "El Pisco es un aguardiente de uva peruano/chileno sin envejecer en madera.", icon: "local_bar" },
    { id: 51, text: "IBU mide el amargor de la cerveza (International Bitterness Units).", icon: "science" },
    { id: 52, text: "Las cervezas Stout con nitrógeno tienen una espuma más cremosa.", icon: "coffee_maker" },
    { id: 53, text: "Las IPA deben beberse frescas; el lúpulo se degrada con el tiempo.", icon: "timer" },
    { id: 54, text: "Las cervezas Sour utilizan bacterias para generar acidez refrescante.", icon: "biotech" },
    { id: 55, text: "Solo hay unas pocas cervecerías Trapenses auténticas en el mundo.", icon: "church" },
    { id: 56, text: "Las Lager fermentan a baja temperatura (frío y limpio).", icon: "ac_unit" },
    { id: 57, text: "Las Ale fermentan a alta temperatura (frutales y complejas).", icon: "wb_sunny" },
    { id: 58, text: "El lúpulo es un conservante natural que permitió viajar a la IPA.", icon: "sailing" },
    { id: 59, text: "La malta aporta el color y los azúcares fermentables a la cerveza.", icon: "palette" },
    { id: 60, text: "La levadura define el perfil: plátano en Weissbier, limpio en Lager.", icon: "biotech" },
    { id: 61, text: "Tueste claro en café resalta la acidez; oscuro resalta el cuerpo.", icon: "dark_mode" },
    { id: 62, text: "Robusta tiene más cafeína y cuerpo; Arábica más sabor y acidez.", icon: "bolt" },
    { id: 63, text: "El Espresso requiere 9 bares de presión para crear la crema.", icon: "compress" },
    { id: 64, text: "El Cold Brew es menos ácido porque se extrae con agua fría.", icon: "ac_unit" },
    { id: 65, text: "El método V60 resalta la claridad y las notas florales del café.", icon: "filter_alt" },
    { id: 66, text: "La Prensa Francesa retiene los aceites del café, dando más cuerpo.", icon: "opacity" },
    { id: 67, text: "El agua es el 98% del café; usa agua filtrada o mineral.", icon: "water_drop" },
    { id: 68, text: "Muele el café justo antes de prepararlo para evitar la oxidación.", icon: "cyclone" },
    { id: 69, text: "Piernas densas en un vino indican alto alcohol o mucho azúcar residual.", icon: "format_paint" },
    { id: 70, text: "Viejo Mundo (Europa) = Terroir; Nuevo Mundo = Fruta y Tecnología.", icon: "public" },
    { id: 71, text: "Terroir es la suma de clima, suelo, topografía y mano humana.", icon: "landscape" },
    { id: 72, text: "La fermentación maloláctica da notas de mantequilla al Chardonnay.", icon: "bakery_dining" },
    { id: 73, text: "El roble americano aporta coco y eneldo; el francés, vainilla y especias.", icon: "park" },
    { id: 74, text: "El acero inoxidable preserva la fruta pura y la acidez vibrante.", icon: "kitchen" },
    { id: 75, text: "El vino rosado se hace dejando el mosto poco tiempo con las pieles.", icon: "timer" },
    { id: 76, text: "El 'Vino Naranja' es vino blanco hecho como tinto (con pieles).", icon: "history_edu" },
    { id: 77, text: "La biodinámica sigue el calendario lunar para cultivar y vinificar.", icon: "nightlight" },
    { id: 78, text: "Un vino es vegano si no se clarifica con clara de huevo o caseína.", icon: "spa" },
    { id: 79, text: "Todos los vinos tienen sulfitos naturales; se añaden para conservar.", icon: "science" },
    { id: 80, text: "Sirve los blancos a 8-10°C; si están muy fríos no huelen a nada.", icon: "thermostat" },
    { id: 81, text: "Sirve los tintos a 16-18°C; si están calientes, el alcohol molesta.", icon: "thermostat" },
    { id: 82, text: "El espumoso debe estar muy frío (6-8°C) para mantener la burbuja.", icon: "ac_unit" },
    { id: 83, text: "Una copa grande ayuda a los vinos tintos complejos a 'respirar'.", icon: "wine_bar" },
    { id: 84, text: "Lava las copas solo con agua caliente para evitar olores a jabón.", icon: "cleaning_services" },
    { id: 85, text: "Guarda el vino tumbado para que el corcho no se seque y encoja.", icon: "horizontal_rule" },
    { id: 86, text: "La luz solar daña la cerveza (olor a mofeta); por eso las botellas son oscuras.", icon: "wb_twilight" },
    { id: 87, text: "Un vino oxidado pierde brillo y huele a manzana pocha o vinagre.", icon: "block" },
    { id: 88, text: "El olor a huevo podrido (reducción) a veces se va al airear el vino.", icon: "air" },
    { id: 89, text: "Brettanomyces es una levadura que da olor a 'establo' o 'cuero'.", icon: "pets" },
    { id: 90, text: "La Acidez Volátil huele a quitaesmalte o pegamento; es un defecto.", icon: "warning_amber" },
    { id: 91, text: "La acidez del vino limpia la grasa de la comida (ej: Champán y fritos).", icon: "cleaning_services" },
    { id: 92, text: "El dulzor (Riesling) calma el picante de la comida asiática.", icon: "icecream" },
    { id: 93, text: "El contraste salado-dulce (Queso azul + Oporto) es delicioso.", icon: "cookie" },
    { id: 94, text: "Los taninos del tinto se suavizan con la proteína de la carne roja.", icon: "lunch_dining" },
    { id: 95, text: "Regla de oro: 'Si crece junto, va bien junto' (Maridaje regional).", icon: "location_on" },
    { id: 96, text: "Usa agua o pan neutro para limpiar el paladar entre catas.", icon: "bakery_dining" },
    { id: 97, text: "Escupir el vino es aceptable y necesario en catas largas profesional.", icon: "delete" },
    { id: 98, text: "Cata en orden: Espumoso > Blanco > Rosado > Tinto > Dulce.", icon: "sort" },
    { id: 99, text: "Tomar notas te ayuda a recordar y entender tu propio gusto.", icon: "edit_note" },
    { id: 100, text: "No hay respuestas incorrectas en lo que TÚ percibes en una copa.", icon: "psychology" }
];
